#!/bin/bash

# Emulates slurm's srun
OPTS=""
CMDS=""

# Extract only --ntasks from options
while (( "$#" )); do
  case "$1" in
     -n|--ntasks)
       OPTS="$OPTS -n $2"
       shift 2
       ;;
     --ntasks=?*)
       OPTS="$OPTS -n ${1:9}"
       shift 1
       ;;
     *)
       CMDS="$CMDS $1"
       shift
       ;;
  esac
done

# Run with mpirun
exec mpirun ${OPTS} ${CMDS}
