[dir]
#  Commonly used base METplus variables
#  Location of METplus code
METPLUS_BASE = {ENV[METPLUS_PATH]}

# Met install location
MET_INSTALL_DIR = {ENV[MET_INSTALL_DIR]}
MET_BASE = {MET_INSTALL_DIR}/share/met
MET_BIN_DIR = {MET_INSTALL_DIR}/bin

# Location of METplus parm directory
METPLUS_PARM_BASE = {ENV[METPLUS_CONF]} 

# Location of configuration files used by MET applications
CONFIG_DIR = {METPLUS_BASE}/parm/met_config

# Location of LOG_DIR
LOG_DIR = {ENV[LOGDIR]}

# Other directories
TMP_DIR = /tmp

[config]
LOG_LEVEL = DEBUG
LOG_MET_VERBOSITY = 2
LOG_MET_OUTPUT_TO_METPLUS = yes

# Order of loops to process data - Options are times, processes
# Not relevant if only one item is in the PROCESS_LIST
# times = run all wrappers in the PROCESS_LIST for a single run time, then
#   increment the run time and run all wrappers again until all times have
#   been evaluated.
# processes = run the first wrapper in the PROCESS_LIST for all times
#   specified, then repeat for the next item in the PROCESS_LIST until all
#   wrappers have been run
LOOP_ORDER = times

