#!/bin/bash
set -eux

if [ $# -eq 0 ] ; then
    echo "ERROR: You must provide the platform as a command-line argument"
    exit 1
fi

SITE=${1}

FV3SAR_DIR=$( pwd )/..
if [ ${SITE} == "cheyenne" ]; then
  export NCEPLIB_DIR=/glade/p/ral/jntp/GMTB/tools/NCEPlibs/20180717/intel-18.0.1/
fi

cd ${FV3SAR_DIR}/sorc
./build_fre-nctools.sh ${SITE}           >& out.build_fre-nctools
./build_orog.sh ${SITE}                  >& out.build_orog
./build_chgres.sh ${SITE}                >& out.build_chgres
#
# The following build several new utilities needed in order to use the 
# new Jim Purser-type grid in the FV3SAR.  The following only works on
# theia for now.  It needs to be ported to other platforms.
#
./build_regional_grid.sh ${SITE}         >& out.build_regional_grid
./build_global_equiv_resol.sh ${SITE}    >& out.build_global_equiv_resol
./build_mosaic_file.sh ${SITE}           >& out.build_mosaic_file


# prepare fixed data directories

cd ${FV3SAR_DIR}
mkdir -p fix/fix_fv3
cd fix

if [ ${SITE} == "theia" ]; then

    ln -sfn /scratch4/NCEPDEV/global/save/glopara/git/fv3gfs/fix/fix_am fix_am

elif [ ${SITE} == "wcoss" || ${SITE} == "dell" ]; then

    ln -sfn /gpfs/dell2/emc/modeling/noscrub/emc.glopara/git/fv3gfs/fix/fix_am fix_am

elif [ ${SITE} == "wcoss_cray" ]; then

    ln -sfn /gpfs/hps3/emc/global/noscrub/emc.glopara/git/fv3gfs/fix/fix_am  fix_am
    echo "module swap pmi pmi/5.0.11" >> ${FV3GFS_DIR}/../NEMSfv3gfs/modulefiles/wcoss_cray/fv3

elif [ ${SITE} == "odin" ]; then

    ln -sfn /scratch/ywang/test_runs/C768_nest/fv3-fix fix_am

elif [ ${SITE} == "cheyenne" ]; then

    ln -sfn /glade/p/ral/jntp/GMTB/FV3GFS_V1_RELEASE/fix/fix_am/ fix_am

elif [ ${SITE} == "jet" ]; then

    ln -sfn regional/build_regional/fix/fix_am fix_am

else

    echo "Unknown site " ${SITE}
    exit

fi
