#!/bin/bash
set -eux

SITE=${1}

FV3GFS_DIR=$( pwd )/..

cd ${FV3GFS_DIR}/sorc
./build_fre-nctools.sh >& out.build_fre-nctools
./build_orog.sh ${SITE} >& out.build_orog
./build_chgres.sh      >& out.build_chgres


cd ${FV3GFS_DIR}/../NEMSfv3gfs/tests
./compile.sh ${FV3GFS_DIR}/../NEMSfv3gfs/FV3 ${SITE} "DEBUG=Y 32BIT=Y" 32bit NO NO >& make.out.32bit

# prepare fixed data directories

cd ${FV3GFS_DIR}
mkdir -p fix/fix_fv3
cd fix

if [ ${SITE} == "theia" ]; then

    ln -fs /scratch4/NCEPDEV/global/save/glopara/git/fv3gfs/fix/fix_am fix_am

elif [ ${SITE} == "wcoss_cray" ]; then

    ln -fs /gpfs/hps3/emc/global/noscrub/emc.glopara/git/fv3gfs/fix/fix_am  fix_am
    echo "module swap pmi pmi/5.0.11" >> ${FV3GFS_DIR}/../NEMSfv3gfs/modulefiles/wcoss_cray/fv3

elif [ ${SITE} == "odin" ]; then

    ln -fs /scratch/ywang/test_runs/C768_nest/fv3-fix fix_am

else
    echo "Unknown site " ${SITE}
    exit
fi
