#!/bin/bash

date
export PS4=' $SECONDS + '
set -xue

#-----------------------------------------------------------------------
export USHaqm=${USHaqm:-${HOMEaqm}/ush}
export PARMaqm=${PARMaqm:-${HOMEaqm}/parm}

export subcyc=0
export pid=${pid:-$$}
export outid=${outid:-"LL$job"}

. ${PARMaqm}/config/var_defns.sh
. $USHaqm/source_util_funcs.sh

export DATA=${DATA:-${DATAROOT}/${jobid}}

mkdir -p ${DATA}
cd ${DATA}

export cycle=${cycle:-t${cyc}z}
export CDATE=${PDY}${cyc}

setpdy.sh
. ./PDY

. $USHaqm/job_preamble.sh

export SENDDBN=${SENDDBN:-YES}
export SENDECF=${SENDECF:-YES}
export SENDCOM=${SENDCOM:-YES}
export SENDDBN_NTC=${SENDDBN_NTC:-NO}

export EXECaqm=${EXECaqm:-${HOMEaqm}/exec}
export PARMaqm=${PARMaqm:-${HOMEaqm}/parm}
export FIXaqm=${FIXaqm:-${HOMEaqm}/fix}
export UTILaqm=${UTILaqm:-${HOMEaqm}/util}

export COMINgfs="${COMINgfs:-$(compath.py ${envir}/gfs/${gfs_ver})}"
export COMIN="${COMIN:-${COMaqm}/${RUN}.${PDY}}"
export COMINm1="${COMIN:-${COMaqm}/${RUN}.${PDYm1}}"
export COMINm2="${COMIN:-${COMaqm}/${RUN}.${PDYm2}}"
export COMOUT="${COMOUT:-${COMaqm}/${RUN}.${PDY}/${cyc}}"

#-----------------------------------------------------------------------
# Get the full path to the file in which this script/function is located 
# (scrfunc_fp), the name of that file (scrfunc_fn), and the directory in
# which the file is located (scrfunc_dir).
#-----------------------------------------------------------------------
#
scrfunc_fp=$( $READLINK -f "${BASH_SOURCE[0]}" )
scrfunc_fn=$( basename "${scrfunc_fp}" )
scrfunc_dir=$( dirname "${scrfunc_fp}" )

env
#-----------------------------------------------------------------------
# Print message indicating entry into script.
#-----------------------------------------------------------------------
#
print_info_msg "
========================================================================
Entering script:  \"${scrfunc_fn}\"
In directory:     \"${scrfunc_dir}\"

This is the J-job script for the task that runs the post-processor (UPP)
on the output files corresponding to a specified forecast hour.
========================================================================"
#
#-----------------------------------------------------------------------
# Set the run directory.
#-----------------------------------------------------------------------
#
DATA="${DATA:-${COMIN}${SLASH_ENSMEM_SUBDIR}/${cyc}}"
#
# If SUB_HOURLY_POST is not set to "TRUE", ensure that the forecast 
# minutes (fmn) are set to "00".  This is necessary in order to pass
# "fmn" into the post ex-script for the calculation of post_time.
#
if [ "${SUB_HOURLY_POST}" != "TRUE" ]; then
  export fmn="00"
fi
#
mkdir -p ${COMOUT}

export DATA_FHR="${DATA:-$COMOUT}/$fhr"

#check_for_preexist_dir_file "${DATA_FHR}" "delete"

mkdir -p ${DATA_FHR}

cd ${DATA_FHR}

#
#-----------------------------------------------------------------------
# Make sure that fhr is a non-empty string consisting of only digits.  
#-----------------------------------------------------------------------
#
export fhr=$( printf "%s" "${fhr}" | $SED -n -r -e "s/^([0-9]+)$/\1/p" )
if [ -z "$fhr" ]; then
  print_err_msg_exit "\
The forecast hour (fhr) must be a non-empty string consisting of only 
digits:
  fhr = \"${fhr}\""
fi
#
#-----------------------------------------------------------------------
# Call the ex-script for this J-job and pass to it the necessary varia-
# bles.
#-----------------------------------------------------------------------
#
startmsg
${HOMEaqm}/scripts/exaqm_post.sh 
export err=$?; err_chk
#
#-----------------------------------------------------------------------
#
if [ ${#FCST_LEN_CYCL[@]} -gt 1 ]; then
  cyc_mod=$(( ${cyc} - ${DATE_FIRST_CYCL:8:2} ))
  CYCLE_IDX=$(( ${cyc_mod} / ${INCR_CYCL_FREQ} ))
  FCST_LEN_HRS=${FCST_LEN_CYCL[$CYCLE_IDX]}
fi

#
fcst_len_hrs=$( printf "%03d" "${FCST_LEN_HRS}" )
#
#======================================================================
msg="JOB ${job} HAS COMPLETED NORMALLY."
postmsg "${msg}"

if [ -e "${pgmout}" ]; then
   cat ${pgmout}
fi

if [ "${KEEPDATA}" != "YES" ]; then
   rm -rf ${DATA}
fi
#=======================================================================
# Print exit message
print_info_msg "
========================================================================
Exiting script:  \"${scrfunc_fn}\"
In directory:    \"${scrfunc_dir}\"
========================================================================"
#
#-----------------------------------------------------------------------
# Restore the shell options saved at the beginning of this script/func-
# tion.
#-----------------------------------------------------------------------
#
{ restore_shell_opts; } > /dev/null 2>&1

date
