#!/bin/bash

date
export PS4=' $SECONDS + '
set -xue

#-----------------------------------------------------------------------
# Source the variable definitions file and the bash utility functions.
#-----------------------------------------------------------------------
export USHaqm=${USHaqm:-${HOMEaqm}/ush}
export PARMaqm=${PARMaqm:-${HOMEaqm}/parm}

export subcyc=0
export SLASH_ENSMEM_SUBDIR=''
export pid=${pid:-$$}
export outid=${outid:-"LL$job"}

. ${PARMaqm}/config/var_defns.sh

. $USHaqm/source_util_funcs.sh

export DATAROOT="${DATAROOT:-${DATAROOT_dfv}}"
export DATA=${DATA:-${DATAROOT}/${jobid}}

mkdir -p ${DATA}
cd ${DATA}

export cycle=${cycle:-t${cyc}z}
export CDATE=${PDY}${cyc}

setpdy.sh
. ./PDY

. $USHaqm/job_preamble.sh

export FIXaqmconfig="${FIXaqmbio:-${HOMEaqm}/fix/aqm/epa/data}"
export FIXaqmbio="${FIXaqmbio:-${HOMEaqm}/fix/bio}"
export FIXaqmdust="${FIXaqmdust:-${HOMEaqm}/fix/dust}"
export FIXaqmcanopy="${FIXaqmcanopy:-${HOMEaqm}/fix/canopy}"
export FIXaqmnexus="${FIXaqmnexus:-${HOMEaqm}/fix/nexus}"
export FIXaqmnexus_gfs_sfc="${FIXaqmnexus:-${HOMEaqm}/fix/gfs}"

export EXECaqm=${EXECaqm:-${HOMEaqm}/exec}
export PARMaqm=${PARMaqm:-${HOMEaqm}/parm}
export FIXaqm=${FIXaqm:-${HOMEaqm}/fix}
export UTILaqm=${UTILaqm:-${HOMEaqm}/util}

export COMINemis="${COMINemis:-${COMIN}/emission}"
export COMINgfs="${COMINgfs:-$(compath.py ${envir}/gfs/${gfs_ver})}"
export COMIN="${COMIN:-$(compath.py -o ${NET}/${model_ver}/${RUN}.${PDY})}"
export COMINm1="${COMINm1:-$(compath.py -o ${NET}/${model_ver}/${RUN}.${PDYm1})}"
export COMINm2="${COMINm1:-$(compath.py -o ${NET}/${model_ver}/${RUN}.${PDYm2})}"
export COMOUT="${COMOUT:-$(compath.py -o ${NET}/${model_ver}/${RUN}.${PDY}/${cyc})}"

#
#-----------------------------------------------------------------------
# Save current shell options (in a global array).  Then set new options
# for this script/function.
#-----------------------------------------------------------------------
#
{ save_shell_opts; . $USHaqm/preamble.sh; } > /dev/null 2>&1
#
#-----------------------------------------------------------------------
# Get the full path to the file in which this script/function is located 
# (scrfunc_fp), the name of that file (scrfunc_fn), and the directory in
# which the file is located (scrfunc_dir).
#-----------------------------------------------------------------------
#
scrfunc_fp=$( $READLINK -f "${BASH_SOURCE[0]}" )
scrfunc_fn=$( basename "${scrfunc_fp}" )
scrfunc_dir=$( dirname "${scrfunc_fp}" )

env
#-----------------------------------------------------------------------
# Print message indicating entry into script.
#-----------------------------------------------------------------------
#
print_info_msg "
========================================================================
Entering script:  \"${scrfunc_fn}\"
In directory:     \"${scrfunc_dir}\"

This is the J-job script for the task that generates the emission files 
using NEXUS which will output for FV3 (in NetCDF format).
========================================================================"
#
#-----------------------------------------------------------------------
# Set the name of and create the directory in which the output from this
# script will be placed (if it doesn't already exist).
#-----------------------------------------------------------------------
#
export INPUT_DATA="${INPUT_DATA:-${COMIN}/${cyc}/NEXUS}"
mkdir -p ${INPUT_DATA}
#
#-----------------------------------------------------------------------
# Set the run directory
#-----------------------------------------------------------------------
#
DATA="${DATA:-${COMIN}${SLASH_ENSMEM_SUBDIR}/tmp_NEXUS_EMISSION_${nspt}}"
#
#-----------------------------------------------------------------------
# Set environment only when RUN_TASK_NEXUS_GFS_SFC is false.
#-----------------------------------------------------------------------
#
if [ "${RUN_TASK_NEXUS_GFS_SFC}" = "FALSE" ]; then
  export TIME_OFFSET_HRS=${NEXUS_GFS_SFC_OFFSET_HRS:-0}
  yyyymmdd=${PDY}
  hh=${cyc}
  export GFS_SFC_CDATE=$( $DATE_UTIL --utc --date "${yyyymmdd} ${hh} UTC - ${TIME_OFFSET_HRS} hours" "+%Y%m%d%H" )
  SLASH_ENSMEM_SUBDIR=${SLASH_ENSMEM_SUBDIR:-""}
  export GFS_SFC_STAGING_DIR="${COMIN}${SLASH_ENSMEM_SUBDIR}/tmp_NEXUS_GFS_SFC}"
fi
#
#-----------------------------------------------------------------------
# Call the ex-script for this J-job.
#-----------------------------------------------------------------------
#
startmsg
${HOMEaqm}/scripts/exaqm_nexus_emission.sh
export err=$?; err_chk
#
if [ "${KEEPDATA}" = "FALSE" ]; then
   cd ${DATAROOT}
   rm -rf $DATA
fi
# Print exit message
print_info_msg "
========================================================================
Exiting script:  \"${scrfunc_fn}\"
In directory:    \"${scrfunc_dir}\"
========================================================================"
#-----------------------------------------------------------------------
#
# Restore the shell options saved at the beginning of this script/func-
# tion.
#
#-----------------------------------------------------------------------
#
{ restore_shell_opts; } > /dev/null 2>&1

