#!/bin/bash

date
export PS4=' $SECONDS + '
set -xue

#-----------------------------------------------------------------------
export USHaqm=${USHaqm:-${HOMEaqm}/ush}
export PARMaqm=${PARMaqm:-${HOMEaqm}/parm}

export subcyc=0
export pid=${pid:-$$}
export outid=${outid:-"LL$job"}

. ${PARMaqm}/config/var_defns.sh
. $USHaqm/source_util_funcs.sh

export DATA=${DATA:-${DATAROOT}/${jobid}}
mkdir -p ${DATA}
cd ${DATA}

export cycle=${cycle:-t${cyc}z}

setpdy.sh
. ./PDY

export CDATE=${PDY}${cyc}

. $USHaqm/job_preamble.sh 

export SENDDBN=${SENDDBN:-YES}
export SENDECF=${SENDECF:-YES}
export SENDCOM=${SENDCOM:-YES}
export SENDDBN_NTC=${SENDDBN_NTC:-NO}

export EXECaqm=${EXECaqm:-${HOMEaqm}/exec}
export PARMaqm=${PARMaqm:-${HOMEaqm}/parm}
export FIXaqm=${FIXaqm:-${HOMEaqm}/fix}
export UTILaqm=${UTILaqm:-${HOMEaqm}/util}

export COMIN="${COMIN:-${COMaqm}/${RUN}.${PDY}}"
export COMINm1="${COMIN:-${COMaqm}/${RUN}.${PDYm1}}"
export COMINm2="${COMIN:-${COMaqm}/${RUN}.${PDYm2}}"
export COMOUT="${COMOUT:-${COMaqm}/${RUN}.${PDY}/${cyc}}"

#-----------------------------------------------------------------------
# Get the full path to the file in which this script/function is located 
# (scrfunc_fp), the name of that file (scrfunc_fn), and the directory in
# which the file is located (scrfunc_dir).
#-----------------------------------------------------------------------
#
scrfunc_fp=$( $READLINK -f "${BASH_SOURCE[0]}" )
scrfunc_fn=$( basename "${scrfunc_fp}" )
scrfunc_dir=$( dirname "${scrfunc_fp}" )

env
#-----------------------------------------------------------------------
# Print message indicating entry into script.
#-----------------------------------------------------------------------
#
print_info_msg "
========================================================================
Entering script:  \"${scrfunc_fn}\"
In directory:     \"${scrfunc_dir}\"

This is the J-job script for the task that runs a forecast with FV3 for 
the specified cycle.
========================================================================"
#
#-----------------------------------------------------------------------
# Create the INPUT and RESTART directories under the run directory.
#-----------------------------------------------------------------------
#

mkdir -p ${DATA}/INPUT
mkdir -p ${DATA}/RESTART

export INPUT_DATA="${INPUT_DATA:-${COMIN}/${cyc}}"
#
#-----------------------------------------------------------------------
# Call the ex-script for this J-job and pass to it the necessary varia-
# bles.
#-----------------------------------------------------------------------
#
startmsg
${HOMEaqm}/scripts/exaqm_forecast.sh
export err=$?; err_chk
#

# Print exit message
print_info_msg "
========================================================================
Exiting script:  \"${scrfunc_fn}\"
In directory:    \"${scrfunc_dir}\"
========================================================================"
#
#-----------------------------------------------------------------------
# Restore the shell options saved at the beginning of this script/func-
# tion.
#-----------------------------------------------------------------------
#
{ restore_shell_opts; } > /dev/null 2>&1
