#!/bin/bash

date
export PS4='$SECONDS + '
set -xue

##############################################
# Obtain unique process id (pid) and make temp directory
##############################################
export pid=${pid:-$$}
export outid=${outid:-"LL$job"}

export DATA=${DATA:-${DATAROOT}/${jobid:?}}
mkdir -p $DATA
cd $DATA

##############################################
# Run setpdy and initialize PDY variables
##############################################
export cycle="t${cyc}z"
setpdy.sh
. ./PDY

env
##############################################
# Set variables used in the script
##############################################
${HOMEaqm}/scripts/exaqm_data_cleanup.sh
status=$?
[[ $status -ne 0 ]] && exit $status

##########################################
# Remove the Temporary working directory
##########################################
cd $DATAROOT
[[ $KEEPDATA = "NO" ]] && rm -rf $DATA

date
