#!/bin/bash

date
export PS4=' $SECONDS + '
set -xue

#-----------------------------------------------------------------------
export USHaqm=${USHaqm:-${HOMEaqm}/ush}
export PARMaqm=${PARMaqm:-${HOMEaqm}/parm}

export subcyc=0
export pid=${pid:-$$}
export outid=${outid:-"LL$job"}

. ${PARMaqm}/config/var_defns.sh
. $USHaqm/source_util_funcs.sh

export DATA=${DATA:-${DATAROOT}/${jobid}}

mkdir -p ${DATA}
cd ${DATA}

export cycle=${cycle:-t${cyc}z}

setpdy.sh
. ./PDY

. $USHaqm/job_preamble.sh

export SENDDBN=${SENDDBN:-YES}
export SENDECF=${SENDECF:-YES}
export SENDCOM=${SENDCOM:-YES}
export SENDDBN_NTC=${SENDDBN_NTC:-NO}

export EXECaqm=${EXECaqm:-${HOMEaqm}/exec}
export PARMaqm=${PARMaqm:-${HOMEaqm}/parm}
export FIXaqm=${FIXaqm:-${HOMEaqm}/fix}
export UTILaqm=${UTILaqm:-${HOMEaqm}/util}

export COMIN="${COMIN:-${COMaqm}/${RUN}.${PDY}}"
export COMINm1="${COMIN:-${COMaqm}/${RUN}.${PDYm1}}"
export COMINm2="${COMIN:-${COMaqm}/${RUN}.${PDYm2}}"
export COMOUT="${COMOUT:-${COMaqm}/${RUN}.${PDY}/${cyc}}"

export DCOMINairnow="${DCOMINairnow:-${DCOMROOT}}"

export COMINbicor=${COMINbicor:-${COMaqm}}
export COMOUTbicor=${COMOUTbicor:-${COMaqm}}

#-----------------------------------------------------------------------
# Get the full path to the file in which this script/function is located 
# (scrfunc_fp), the name of that file (scrfunc_fn), and the directory in
# which the file is located (scrfunc_dir).
#-----------------------------------------------------------------------
#
scrfunc_fp=$( $READLINK -f "${BASH_SOURCE[0]}" )
scrfunc_fn=$( basename "${scrfunc_fp}" )
scrfunc_dir=$( dirname "${scrfunc_fp}" )

env
#-----------------------------------------------------------------------
# Print message indicating entry into script.
#-----------------------------------------------------------------------
#
print_info_msg "
========================================================================
Entering script:  \"${scrfunc_fn}\"
In directory:     \"${scrfunc_dir}\"

This is the J-job script for the task that runs BIAS-CORRECTION-O3.
========================================================================"
#
#-----------------------------------------------------------------------
# Set the run directory.
#-----------------------------------------------------------------------
#
DATA="${DATA:-${COMIN}${SLASH_ENSMEM_SUBDIR}/tmp_BIAS_CORRECTION_O3}"

if [ "${cyc}" = "06" ] || [ "${cyc}" = "12" ]; then
  export PCOM=${PCOM:-${COMOUT}/wmo}
  if [ ! -d "${PCOM}" ]; then 
      mkdir -p "${PCOM}"
  fi
fi

export PARMaqm_utils="${PARMaqm_utils:-${HOMEaqm}/parm/aqm_utils}"

TMP_STDAY=`${NDATE} -8760 ${PDY}${cyc} | cut -c1-8`  # 1 year back
export BC_STDAY=${BC_STDAY:-${TMP_STDAY}}
#
#-----------------------------------------------------------------------
# Call the ex-script for this J-job and pass to it the necessary varia-
# bles.
#-----------------------------------------------------------------------
#
${HOMEaqm}/scripts/exaqm_bias_correction_o3.sh
export err=$?; err_chk
#
#======================================================================
msg="JOB ${job} HAS COMPLETED NORMALLY."
postmsg "${msg}"

if [ "${KEEPDATA}" != "YES" ]; then
   rm -rf ${DATA}
fi
#=======================================================================
# Print exit message
print_info_msg "
========================================================================
Exiting script:  \"${scrfunc_fn}\"
In directory:    \"${scrfunc_dir}\"
========================================================================"
#
#-----------------------------------------------------------------------
# Restore the shell options saved at the beginning of this script/func-
# tion.
#-----------------------------------------------------------------------
#
{ restore_shell_opts; } > /dev/null 2>&1

date
