#!/usr/bin/env bash

#
#-----------------------------------------------------------------------
#
# The J-Job that generates input NetCDF grid files for running the
# regional configuration of FV3 
#
# Run-time environment variables:
#
#    GLOBAL_VAR_DEFNS_FP
#    DATA
#
# Experiment variables
#
#  user:
#    USHdir
#    SCRIPTSdir
#
#  workflow:
#    PREEXISTING_DIR_METHOD
#
#  task_make_grid:
#    GRID_DIR
#
#-----------------------------------------------------------------------
#

#
#-----------------------------------------------------------------------
#
# Source the variable definitions file and the bash utility functions.
#
#-----------------------------------------------------------------------
#
. $USHdir/source_util_funcs.sh
for sect in user nco workflow task_make_grid ; do
  source_yaml ${GLOBAL_VAR_DEFNS_FP} ${sect}
done
. $USHdir/job_preamble.sh
#
#-----------------------------------------------------------------------
#
# Save current shell options (in a global array).  Then set new options
# for this script/function.
#
#-----------------------------------------------------------------------
#
{ save_shell_opts; . $USHdir/preamble.sh; } > /dev/null 2>&1
#
#-----------------------------------------------------------------------
#
# Get the full path to the file in which this script/function is located 
# (scrfunc_fp), the name of that file (scrfunc_fn), and the directory in
# which the file is located (scrfunc_dir).
#
#-----------------------------------------------------------------------
#
scrfunc_fp=$( $READLINK -f "${BASH_SOURCE[0]}" )
scrfunc_fn=$( basename "${scrfunc_fp}" )
scrfunc_dir=$( dirname "${scrfunc_fp}" )
#
#-----------------------------------------------------------------------
#
# Print message indicating entry into script.
#
#-----------------------------------------------------------------------
#
print_info_msg "
========================================================================
Entering script:  \"${scrfunc_fn}\"
In directory:     \"${scrfunc_dir}\"

This is the J-job script for the task that generates grid files.
========================================================================"
#
#-----------------------------------------------------------------------
#
# Create the (cycle-independent) subdirectories under the experiment
# directory (EXPTDIR) that are needed by the various steps and substeps
# in this script.
#
#-----------------------------------------------------------------------
#
check_for_preexist_dir_file "${GRID_DIR}" "${PREEXISTING_DIR_METHOD}"
mkdir -p "${GRID_DIR}"
#
#-----------------------------------------------------------------------
#
# Create a work directory.
#
#-----------------------------------------------------------------------
#
DATA="${DATA:-${GRID_DIR}/tmp}"
mkdir -p "$DATA"
#
#-----------------------------------------------------------------------
#
# Call the ex-script for this J-job and pass to it the necessary varia-
# bles.
#
#-----------------------------------------------------------------------
#
${SCRIPTSdir}/exregional_make_grid.sh || \
print_err_msg_exit "\
Call to ex-script corresponding to J-job \"${scrfunc_fn}\" failed."
#
#-----------------------------------------------------------------------
#
# Create a flag file to make rocoto aware that the make_grid task has 
# successfully completed (so that other tasks that depend on it can be
# launched).  
#
# Although we can use the <taskdep> tag to make other tasks depend on 
# the successful completion of make_grid, it turns out that the <task-
# dep> tag assumes that the task it specifies (in this case make_grid)
# runs for the same set of cycles as the one in which it appears as a 
# dependency.  Thus, if we use <taskdep> in a cycle-dependent task in 
# the workflow to make it depend on the make_grid, then the workflow 
# will wait for make_grid to run for each cycle for which that cycle-de-
# pendent task is defined before running the task.  But since make_grid
# will not run for each cycle (except possibly for the very first one),
# the cycle-dependent task will not be able to run for any of the cycles
# except the first one.  For this reason, we cannot use the <taskdep> 
# tag to make other cycle-dependent tasks depend on make_grid and must
# instead use a flag file.
#
#-----------------------------------------------------------------------
#
touch "$GRID_DIR/make_grid_task_complete.txt"
#
#-----------------------------------------------------------------------
#
# Run job postamble.
#
#-----------------------------------------------------------------------
#
job_postamble
#
#-----------------------------------------------------------------------
#
# Restore the shell options saved at the beginning of this script/func-
# tion.
#
#-----------------------------------------------------------------------
#
{ restore_shell_opts; } > /dev/null 2>&1

