#!/bin/bash

#
#-----------------------------------------------------------------------
#
# This script copies files from various directories into the experiment
# directory, creates links to some of them, and modifies others (e.g. 
# templates) to customize them for the current experiment setup.
#
#-----------------------------------------------------------------------
#

#
#-----------------------------------------------------------------------
#
# Source the variable definitions script and the function definitions
# file.
#
#-----------------------------------------------------------------------
#
. ${SCRIPT_VAR_DEFNS_FP}
. $USHDIR/source_funcs.sh
#
#-----------------------------------------------------------------------
#
# Save current shell options (in a global array).  Then set new options
# for this script/function.
#
#-----------------------------------------------------------------------
#
{ save_shell_opts; set -u -x; } > /dev/null 2>&1
#
#-----------------------------------------------------------------------
#
# Get the name of this script as well as the directory in which it is 
# located.
#
#-----------------------------------------------------------------------
#
script_path=$( readlink -f "${BASH_SOURCE[0]}" )
script_name=$( basename "${script_path}" )
script_dir=$( dirname "${script_path}" )
print_info_msg "
========================================================================
Entering script:  \"${script_path}\"

This is the J-job script for the task that runs a forecast with FV3 for 
the specified cycle.
========================================================================"
#
#-----------------------------------------------------------------------
#
# Create the INPUT and RESTART directories under the cycle directory.
#
#-----------------------------------------------------------------------
#
mkdir_vrfy -p ${CYCLE_DIR}/INPUT
mkdir_vrfy -p ${CYCLE_DIR}/RESTART
#
#-----------------------------------------------------------------------
#
# Call the ex-script for this J-job and pass to it the necessary varia-
# bles.
#
#-----------------------------------------------------------------------
#
$SCRIPTSDIR/exregional_run_fv3.sh \
  CYCLE_DIR="${CYCLE_DIR}" || \
print_err_msg_exit "\
Call to ex-script corresponding to J-job \"${script_name}\" failed."
#
#-----------------------------------------------------------------------
#
# Print exit message.
#
#-----------------------------------------------------------------------
#
print_info_msg "\n\
========================================================================
Exiting script:  \"${script_path}\"
========================================================================"
#
#-----------------------------------------------------------------------
#
# Restore the shell options saved at the beginning of this script/func-
# tion.
#
#-----------------------------------------------------------------------
#
{ restore_shell_opts; } > /dev/null 2>&1

