#!/bin/bash

#
#-----------------------------------------------------------------------
#
#
#
#-----------------------------------------------------------------------
#

#
#-----------------------------------------------------------------------
#
# Source the variable definitions file and the bash utility functions.
#
#-----------------------------------------------------------------------
#
. $USHdir/source_util_funcs.sh
source_config_for_task "task_run_vx_ensgrid|task_run_vx_enspoint" ${GLOBAL_VAR_DEFNS_FP}
. $USHdir/job_preamble.sh
#
#-----------------------------------------------------------------------
#
# Save current shell options (in a global array).  Then set new options
# for this script/function.
#
#-----------------------------------------------------------------------
#
{ save_shell_opts; . $USHdir/preamble.sh; } > /dev/null 2>&1
#
#-----------------------------------------------------------------------
#
# Get the full path to the file in which this script/function is located 
# (scrfunc_fp), the name of that file (scrfunc_fn), and the directory in
# which the file is located (scrfunc_dir).
#
#-----------------------------------------------------------------------
#
scrfunc_fp=$( $READLINK -f "${BASH_SOURCE[0]}" )
scrfunc_fn=$( basename "${scrfunc_fp}" )
scrfunc_dir=$( dirname "${scrfunc_fp}" )
#
#-----------------------------------------------------------------------
#
# Print message indicating entry into script.
#
#-----------------------------------------------------------------------
#
print_info_msg "
========================================================================
Entering script:  \"${scrfunc_fn}\"
In directory:     \"${scrfunc_dir}\"

This is the J-job script for the task that runs either METplus's 
gen_ens_prod tool or its ensemble_stat tool for ensemble verification.
========================================================================"
#
#-----------------------------------------------------------------------
#
# Set the name of the MET/METplus tool this task will call.  (Note: "sc"
# is for "snake case", i.e. using underscores as separators, and "pc" is
# for "Pascal case", i.e. no separators but first letter of each word
# capitalized.)
#
#-----------------------------------------------------------------------
#
valid_vals_MET_TOOL=( "GENENSPROD" "ENSEMBLESTAT" )
check_var_valid_value "MET_TOOL" "valid_vals_MET_TOOL"

if [ "${MET_TOOL}" = "GENENSPROD" ]; then
  met_tool_sc="gen_ens_prod"
  met_tool_pc="GenEnsProd"
elif [ "${MET_TOOL}" = "ENSEMBLESTAT" ]; then
  met_tool_sc="ensemble_stat"
  met_tool_pc="EnsembleStat"
fi
#
#-----------------------------------------------------------------------
#
# Call the ex-script for this J-job and pass to it the necessary varia-
# bles.
#
#-----------------------------------------------------------------------
#
$SCRIPTSdir/exregional_run_met_genensprod_or_ensemblestat.sh \
  met_tool_sc="${met_tool_sc}" \
  met_tool_pc="${met_tool_pc}" || \
print_err_msg_exit "\
Call to ex-script corresponding to J-job \"${scrfunc_fn}\" failed."
#
#-----------------------------------------------------------------------
#
# Run job postamble.
#
#-----------------------------------------------------------------------
#
job_postamble
#
#-----------------------------------------------------------------------
#
# Restore the shell options saved at the beginning of this script/func-
# tion.
#
#-----------------------------------------------------------------------
#
{ restore_shell_opts; } > /dev/null 2>&1

