#!/bin/bash

#
#-----------------------------------------------------------------------
#
# This J-JOB script plots graphics using pygraf library
#
#-----------------------------------------------------------------------

#
#-----------------------------------------------------------------------
#
# Source the variable definitions file and the bash utility functions.
#
#-----------------------------------------------------------------------
#
. $USHdir/source_util_funcs.sh
source_config_for_task "task_run_graphics" ${GLOBAL_VAR_DEFNS_FP}
. $USHdir/job_preamble.sh
#
#-----------------------------------------------------------------------
#
# Save current shell options (in a global array).  Then set new options
# for this script/function.
#
#-----------------------------------------------------------------------
#
{ save_shell_opts; . $USHdir/preamble.sh; } > /dev/null 2>&1
#
#-----------------------------------------------------------------------
#
# Get the full path to the file in which this script/function is located 
# (scrfunc_fp), the name of that file (scrfunc_fn), and the directory in
# which the file is located (scrfunc_dir).
#
#-----------------------------------------------------------------------
#
scrfunc_fp=$( readlink -f "${BASH_SOURCE[0]}" )
scrfunc_fn=$( basename "${scrfunc_fp}" )
scrfunc_dir=$( dirname "${scrfunc_fp}" )
#
#-----------------------------------------------------------------------
#
# Print message indicating entry into script.
#
#-----------------------------------------------------------------------
#
print_info_msg "
========================================================================
Entering script:  \"${scrfunc_fn}\"
In directory:     \"${scrfunc_dir}\"
This is the J-job script for plotting using pygraf
========================================================================"
#
#-----------------------------------------------------------------------
#
# Set the run directory and post directories.
#
#-----------------------------------------------------------------------
#
if [ "${RUN_ENVIR}" = "nco" ]; then
  DATA="${COMOUT}/pyprd"
  export ZIP_DIR="${COMOUT}/nclprd"
  export POSTPRD_DIR="${COMOUT}/${ENSPROD:-}"
else
  DATA="${COMOUT}${SLASH_ENSMEM_SUBDIR}/pyprd"
  export ZIP_DIR="${COMOUT}${SLASH_ENSMEM_SUBDIR}/nclprd"
  export POSTPRD_DIR="${DATA}/postprd"
fi
COMOUT="${COMOUT}${SLASH_ENSMEM_SUBDIR}"
export COMOUT_mem0="${ENSCTRL_COMOUT_BASEDIR}/$RUN.$PDY/$cyc"
#
#
#-----------------------------------------------------------------------
#
# Call the ex-script for this J-job and pass to it the necessary varia-
# bles.
#
#-----------------------------------------------------------------------
#
$SCRIPTSdir/exregional_run_graphics.sh || print_err_msg_exit "\
Call to ex-script corresponding to J-job \"${scrfunc_fn}\" failed."
#
#-----------------------------------------------------------------------
#
# Run job postamble.
#
#-----------------------------------------------------------------------
#
job_postamble
#
#-----------------------------------------------------------------------
#
# Restore the shell options saved at the beginning of this script/func-
# tion.
#
#-----------------------------------------------------------------------
#
{ restore_shell_opts; } > /dev/null 2>&1
