#
# TEST PURPOSE/DESCRIPTION:
# ------------------------
#
# This test checks the capability of the workflow to retrieve from NOAA 
# HPSS netcdf-formatted output files generated by the FV3GFS external 
# model (FCST_LEN_HRS>=40).
#

RUN_ENVIR="community"
PREEXISTING_DIR_METHOD="rename"

PREDEF_GRID_NAME="RRFS_CONUS_25km"
CCPP_PHYS_SUITE="FV3_GFS_v16"

EXTRN_MDL_NAME_ICS="FV3GFS"
FV3GFS_FILE_FMT_LBCS="netcdf"
EXTRN_MDL_NAME_LBCS="FV3GFS"
FV3GFS_FILE_FMT_ICS="netcdf"

DATE_FIRST_CYCL="20220601"
DATE_LAST_CYCL="20220601"
CYCL_HRS=( "12" )

FCST_LEN_HRS="48"
LBC_SPEC_INTVL_HRS="12"
