#! /bin/sh
#PBS -A epic
#PBS -l select=1:mpiprocs=24:ncpus=24
#PBS -q regular
#PBS -l walltime=00:20:00
#PBS -j oe -o make_grid.log
#PBS -N make_grid

export GLOBAL_VAR_DEFNS_FP=$PWD'/../var_defns.sh'
export USHdir=`grep USHdir $GLOBAL_VAR_DEFNS_FP | cut -d\' -f2`
export JOBSdir=`grep JOBSdir $GLOBAL_VAR_DEFNS_FP | cut -d\' -f2`

$USHdir/load_modules_run_task.sh "make_grid" $JOBSdir/JREGIONAL_MAKE_GRID
