#
#-----------------------------------------------------------------------
#
# Set the system directory (i.e. location on disk, not on HPSS) in which
# the files generated by the external model specified by EXTRN_MDL_-
# NAME_ICS that are necessary for generating initial condition (IC)
# and surface files for the FV3SAR are stored (usually for a limited 
# time, e.g. for the GFS external model, 2 weeks on WCOSS and 2 days on
# theia).  If for a given cycle these files are available in this system
# directory, they will be copied over to a subdirectory within the cy-
# cle's run directory.  If these files are not available in the system
# directory, then we search for them elsewhere, e.g. in the mass store
# (HPSS).
#
#-----------------------------------------------------------------------
#
if [ "${RUN_ENVIR}" = "nco" ]; then

  EXTRN_MDL_FILES_SYSBASEDIR_ICS="$COMINgfs"

else

  case ${EXTRN_MDL_NAME_ICS} in
  
  
  "GSMGFS")
    case $MACHINE in
    "WCOSS_C")
      EXTRN_MDL_FILES_SYSBASEDIR_ICS=""
      ;;
    "THEIA")
      EXTRN_MDL_FILES_SYSBASEDIR_ICS=""
      ;;
    "HERA")
      EXTRN_MDL_FILES_SYSBASEDIR_ICS=""
      ;;
    "JET")
      EXTRN_MDL_FILES_SYSBASEDIR_ICS=""
      ;;
    "ODIN")
      EXTRN_MDL_FILES_SYSBASEDIR_ICS=""
      ;;
    *)
      print_err_msg_exit "\
The system directory in which to look for the files generated by the ex-
ternal model specified by EXTRN_MDL_NAME_ICS has not been specified for
this machine and external model combination:
  MACHINE = \"$MACHINE\"
  EXTRN_MDL_NAME_ICS = \"${EXTRN_MDL_NAME_ICS}\"
"
      ;;
    esac
    ;;
  
  
  "FV3GFS")
    case $MACHINE in
    "WCOSS_C")
      EXTRN_MDL_FILES_SYSBASEDIR_ICS="/gpfs/hps/nco/ops/com/gfs/prod"
      ;;
    "THEIA")
      EXTRN_MDL_FILES_SYSBASEDIR_ICS="/scratch4/NCEPDEV/rstprod/com/gfs/prod"
      ;;
    "HERA")
      EXTRN_MDL_FILES_SYSBASEDIR_ICS="/scratch2/NCEPDEV/fv3-cam/noscrub/Eric.Rogers/prfv3rt1"
      ;;
    "JET")
      EXTRN_MDL_FILES_SYSBASEDIR_ICS="/lfs3/projects/hpc-wof1/ywang/regional_fv3/gfs"
      ;;
    "ODIN")
      EXTRN_MDL_FILES_SYSBASEDIR_ICS="/scratch/ywang/test_runs/FV3_regional/gfs"
      ;;
    *)
      print_err_msg_exit "\
The system directory in which to look for the files generated by the ex-
ternal model specified by EXTRN_MDL_NAME_ICS has not been specified for
this machine and external model combination:
  MACHINE = \"$MACHINE\"
  EXTRN_MDL_NAME_ICS = \"${EXTRN_MDL_NAME_ICS}\"
"
      ;;
    esac
    ;;
  
  
  "RAPX")
    case $MACHINE in
    "THEIA")
      EXTRN_MDL_FILES_SYSBASEDIR_ICS="/scratch4/BMC/public/data/gsd/rr/full/wrfnat"
      ;;
    "HERA")
      EXTRN_MDL_FILES_SYSBASEDIR_ICS="/scratch2/BMC/public/data/gsd/rap/full/wrfnat"
      ;;
    *)
      print_err_msg_exit "\
The system directory in which to look for the files generated by the ex-
ternal model specified by EXTRN_MDL_NAME_ICS has not been specified for
this machine and external model combination:
  MACHINE = \"$MACHINE\"
  EXTRN_MDL_NAME_ICS = \"${EXTRN_MDL_NAME_ICS}\"
"
      ;;
    esac
    ;;


  "HRRRX")
    case $MACHINE in
    "THEIA")
      EXTRN_MDL_FILES_SYSBASEDIR_ICS="/scratch4/BMC/public/data/gsd/hrrr/conus/wrfnat"
      ;;
    "HERA")
      EXTRN_MDL_FILES_SYSBASEDIR_ICS="/scratch4/BMC/public/data/gsd/hrrr/conus/wrfnat"
      ;;
    *)
      print_err_msg_exit "\
The system directory in which to look for the files generated by the ex-
ternal model specified by EXTRN_MDL_NAME_ICS has not been specified
for this machine and external model combination:
  MACHINE = \"$MACHINE\"
  EXTRN_MDL_NAME_ICS = \"${EXTRN_MDL_NAME_ICS}\"
"
      ;;
    esac
    ;;


  esac

fi
#
#-----------------------------------------------------------------------
#
# Set EXTRN_MDL_LBCS_OFFSET_HRS, which is the number of hours to
# shift the starting time of the external model that provides lateral
# boundary conditions.
#
#-----------------------------------------------------------------------
#
case ${EXTRN_MDL_NAME_LBCS} in
"GSMGFS")
  EXTRN_MDL_LBCS_OFFSET_HRS="0"
  ;;
"FV3GFS")
  EXTRN_MDL_LBCS_OFFSET_HRS="0"
  ;;
"RAPX")
  EXTRN_MDL_LBCS_OFFSET_HRS="3"
  ;;
"HRRRX")
  EXTRN_MDL_LBCS_OFFSET_HRS="0"
  ;;
esac
#
#-----------------------------------------------------------------------
#
# Set the system directory (i.e. location on disk, not on HPSS) in which
# the files generated by the external model specified by EXTRN_MDL_-
# NAME_LBCS that are necessary for generating lateral boundary condition
# (LBC) files for the FV3SAR are stored (usually for a limited time, 
# e.g. for the GFS external model, 2 weeks on WCOSS and 2 days on the-
# ia).  If for a given cycle these files are available in this system 
# directory, they will be copied over to a subdirectory within the cy-
# cle's run directory.  If these files are not available in the system
# directory, then we search for them elsewhere, e.g. in the mass store
# (HPSS).
#
#-----------------------------------------------------------------------
#
if [ "${RUN_ENVIR}" = "nco" ]; then

  EXTRN_MDL_FILES_SYSBASEDIR_LBCS="$COMINgfs"

else

  case ${EXTRN_MDL_NAME_LBCS} in
  
  
  "GSMGFS")
    case $MACHINE in
    "WCOSS_C")
      EXTRN_MDL_FILES_SYSBASEDIR_LBCS=""
      ;;
    "THEIA")
      EXTRN_MDL_FILES_SYSBASEDIR_LBCS=""
      ;;
    "HERA")
      EXTRN_MDL_FILES_SYSBASEDIR_LBCS=""
      ;;
    "JET")
      EXTRN_MDL_FILES_SYSBASEDIR_LBCS=""
      ;;
    "ODIN")
      EXTRN_MDL_FILES_SYSBASEDIR_LBCS=""
      ;;
    *)
      print_err_msg_exit "\
  The system directory in which to look for the files generated by the ex-
  ternal model specified by EXTRN_MDL_NAME_LBCS has not been specified for
  this machine and external model combination:
    MACHINE = \"$MACHINE\"
    EXTRN_MDL_NAME_LBCS = \"${EXTRN_MDL_NAME_LBCS}\"
"
      ;;
    esac
    ;;


  "FV3GFS")
  
    case $MACHINE in
    "WCOSS_C")
      EXTRN_MDL_FILES_SYSBASEDIR_LBCS="/gpfs/hps/nco/ops/com/gfs/prod"
      ;;
    "THEIA")
      EXTRN_MDL_FILES_SYSBASEDIR_LBCS="/scratch4/NCEPDEV/rstprod/com/gfs/prod"
      ;;
    "HERA")
      EXTRN_MDL_FILES_SYSBASEDIR_LBCS="/scratch2/NCEPDEV/fv3-cam/noscrub/Eric.Rogers/prfv3rt1"
      ;;
    "JET")
      EXTRN_MDL_FILES_SYSBASEDIR_LBCS="/lfs3/projects/hpc-wof1/ywang/regional_fv3/gfs"
      ;;
    "ODIN")
      EXTRN_MDL_FILES_SYSBASEDIR_LBCS="/scratch/ywang/test_runs/FV3_regional/gfs"
      ;;
    *)
      print_err_msg_exit "\
  The system directory in which to look for the files generated by the ex-
  ternal model specified by EXTRN_MDL_NAME_LBCS has not been specified for
  this machine and external model combination:
    MACHINE = \"$MACHINE\"
    EXTRN_MDL_NAME_LBCS = \"${EXTRN_MDL_NAME_LBCS}\"
"
      ;;
    esac
    ;;


  "RAPX")
  
    case $MACHINE in
    "THEIA")
      EXTRN_MDL_FILES_SYSBASEDIR_LBCS="/scratch4/BMC/public/data/gsd/rr/full/wrfnat"
      ;;
    "HERA")
      EXTRN_MDL_FILES_SYSBASEDIR_LBCS="/scratch2/BMC/public/data/gsd/rap/full/wrfnat"
      ;;
    *)
      print_err_msg_exit "\
  The system directory in which to look for the files generated by the ex-
  ternal model specified by EXTRN_MDL_NAME_LBCS has not been specified for
  this machine and external model combination:
    MACHINE = \"$MACHINE\"
    EXTRN_MDL_NAME_LBCS = \"${EXTRN_MDL_NAME_LBCS}\"
"
      ;;
    esac
    ;;
  
  
  
  "HRRRX")
  
    case $MACHINE in
    "THEIA")
      EXTRN_MDL_FILES_SYSBASEDIR_LBCS="/scratch4/BMC/public/data/gsd/hrrr/conus/wrfnat"
      ;;
    "HERA")
      EXTRN_MDL_FILES_SYSBASEDIR_LBCS="/scratch2/BMC/public/data/gsd/hrrr/conus/wrfnat"
      ;;
 

    *)
      print_err_msg_exit "\
  The system directory in which to look for the files generated by the ex-
  ternal model specified by EXTRN_MDL_NAME_LBCS has not been specified for
  this machine and external model combination:
    MACHINE = \"$MACHINE\"
    EXTRN_MDL_NAME_LBCS = \"${EXTRN_MDL_NAME_LBCS}\"
"
      ;;
    esac
    ;;
  
  
  
  esac

fi
