.. _fcst5:

Sample Forecast #5: Hurricane Barry
=======================================

Weather Summary
--------------------

Hurricane Barry made landfall in Louisiana on July 11, 2019 as a Category 1 hurricane. It produced widespread flooding in the region and had a peak wind speed of 72 mph and a minimum pressure of 992 hPa. 

**Weather Phenomena:** Flooding, wind, and tornado reports

   * `Storm Prediction Center (SPC) Storm Report for 20190713 <https://www.spc.noaa.gov/climo/reports/190713_rpts.html>`__ 
   * `Storm Prediction Center (SPC) Storm Report for 20190714 <https://www.spc.noaa.gov/climo/reports/190714_rpts.html>`__

.. figure:: https://github.com/ufs-community/ufs-srweather-app/wiki/Tutorial/HurricaneBarry_Making_Landfall.jpg
   :alt: Radar animation of Hurricane Barry making landfall

   *Hurricane Barry Making Landfall*

Tutorial Content
-------------------

Coming Soon!
