.. _fcst3:

Sample Forecast #3: Southern Plains Winter Weather Event
===========================================================

Weather Summary
--------------------

A polar vortex brought arctic air to much of the U.S. and Mexico. A series of cold fronts and vorticity disturbances helped keep this cold air in place for an extended period of time, resulting in record-breaking cold temperatures for many southern states and Mexico. This particular case captures two winter weather disturbances between February 14, 2021 at 06z and February 17, 2021 at 06z that brought several inches of snow to Oklahoma City. A lull on February 16, 2021 resulted in record daily low temperatures. 
   
**Weather Phenomena:** Snow and record-breaking cold temperatures

.. figure:: https://github.com/ufs-community/ufs-srweather-app/wiki/Tutorial/SouthernPlainsWinterWeather.jpg
   :alt: Radar animation of the Southern Plains Winter Weather Event centered over Oklahoma City. Animation starts on February 14, 2021 at 6h00 UTC and ends on February 17, 2021 at 6h00 UTC. 

   *Southern Plains Winter Weather Event Over Oklahoma City*

Tutorial Content
-------------------

Coming Soon! 
