.. _fcst2:

Sample Forecast #2: Cold Air Damming
========================================

Weather Summary
-----------------

Cold air damming occurs when cold dense air is topographically trapped along the leeward (downwind) side of a mountain. Starting on February 3, 2020, weather conditions leading to cold air damming began to develop east of the Appalachian mountains. By February 6-7, 2020, this cold air damming caused high winds, flash flood advisories, and wintery conditions. 

**Weather Phenomena:** Cold air damming

   * `Storm Prediction Center (SPC) Storm Report for 20200205 <https://www.spc.noaa.gov/climo/reports/200205_rpts.html>`_ 
   * `Storm Prediction Center (SPC) Storm Report for 20200206 <https://www.spc.noaa.gov/climo/reports/200206_rpts.html>`_ 
   * `Storm Prediction Center (SPC) Storm Report for 20200207 <https://www.spc.noaa.gov/climo/reports/200207_rpts.html>`_ 

.. figure:: https://github.com/ufs-community/ufs-srweather-app/wiki/Tutorial/ColdAirDamming.jpg
   :alt: Radar animation of precipitation resulting from cold air damming in the southern Appalachian mountains. 

   *Precipitation Resulting from Cold Air Damming East of the Appalachian Mountains*

Tutorial Content 
-------------------

Coming Soon!
