load(pathJoin("intel", os.getenv("intel_ver")))
load(pathJoin("craype", os.getenv("craype_ver")))
load(pathJoin("cray-mpich", os.getenv("cray_mpich_ver")))
load(pathJoin("cray-pals", os.getenv("cray_pals_ver")))

load(pathJoin("jasper", os.getenv("jasper_ver")))
load(pathJoin("libjpeg", os.getenv("libjpeg_ver")))
load(pathJoin("hdf5-C", os.getenv("hdf5_c_ver")))
load(pathJoin("netcdf-C", os.getenv("netcdf_c_ver")))
load(pathJoin("fms", os.getenv("fms_ver")))
load(pathJoin("pio-C", os.getenv("pio_c_ver")))
load(pathJoin("esmf-C", os.getenv("esmf_c_ver")))
load(pathJoin("crtm", os.getenv("crtm_ver")))
load(pathJoin("g2", os.getenv("g2_ver")))
load(pathJoin("g2tmpl", os.getenv("g2tmpl_ver")))
load(pathJoin("ip", os.getenv("ip_ver")))
load(pathJoin("sp", os.getenv("sp_ver")))
load(pathJoin("w3emc", os.getenv("w3emc_ver")))

load(pathJoin("python", os.getenv("python_ver")))

