#!/usr/bin/env bash

#
#-----------------------------------------------------------------------
#
# This script generates grid and orography files in NetCDF format that
# are required as inputs for running the FV3-LAM model (i.e. the FV3 mo-
# del on a regional domain).  It in turn calls three other scripts whose
# file names are specified in the variables grid_gen_scr, orog_gen_scr,
# and orog_fltr_scr and then calls the executable defined in the varia-
# ble shave_exec.  These scripts/executable perform the following tasks:
#
# 1) grid_gen_scr:
#
#    This script generates grid files that will be used by subsequent
#    preprocessing steps.  It places its output in the directory defined.
#    by GRID_DIR.  Note that:
#
#    a) This script creates grid files for each of the 7 tiles of the
#       cubed sphere grid (where tiles 1 through 6 cover the globe, and
#       tile 7 is the regional grid located somewhere within tile 6)
#       even though the forecast will be performed only on tile 7.
#
#    b) The tile 7 grid file that this script creates includes a halo,
#       i.e. a layer of cells beyond the boundary of tile 7).  The width
#       of this halo (i.e. the number of cells in the halo in the direc-
#       tion perpendicular to the boundary of the tile) must be made
#       large enough such that the "shave" steps later below (which take
#       this file as input and generate grid files with thinner halos)
#       have a wide enough starting halo to work with.  More specifical-
#       ly, the FV3-LAM model needs as inputs two grid files: one with a
#       halo that is 3 cells and another with a halo that is 4 cells.
#       wide.  Thus, the halo in the grid file that the grid_gen_scr.
#       script generates must be greater than 4 since otherwise, the
#       shave steps would shave off cells from within the interior of
#       tile 7.  We will let NHW denote the width of the halo in the
#       grid file generated by grid_gen_scr.  The "n" in this variable
#       name denotes number of cells, the "h" is used to indicate that
#       it refers to a halo region, the "w" is used to indicate that it
#       refers to a wide halo (i.e. wider than the 3-cell and 4-cell ha-
#       los that the FV3-LAM model requires as inputs, and the "T7" is
#       used to indicate that the cell count is on tile 7.
#
# 2) orog_gen_scr:
#
#    This script generates the orography file.  It places its output in
#    the directory defined by OROG_DIR.  Note that:
#
#    a) This script generates an orography file only on tile 7.
#
#    b) This orography file contains a halo of the same width (NHW)
#       as the grid file for tile 7 generated by the grid_gen_scr script
#       in the previous step.
#
# 3) orog_fltr_scr:
#
#    This script generates a filtered version of the orography file ge-
#    nerated by the script orog_gen_scr.  This script places its output
#    in the temporary directory defined in WORKDIR_FLTR.  Note that:
#
#    a) The filtered orography file generated by this script contains a
#       halo of the same width (NHW) as the (unfiltered) orography file
#       generated by script orog_gen_scr (and the grid file generated by.
#       grid_gen_scr).
#
#    b) In analogy with the input grid files, the FV3-LAM model needs as
#       input two (filtered) orography files -- one with no halo cells
#       and another with 3.  These are obtained later below by "shaving"
#       off layers of halo cells from the (filtered) orography file ge-
#       nerated in this step.
#
# 4) shave_exec:
#
#    This "shave" executable is called 4 times to generate 4 files from
#    the tile 7 grid file generated by grid_gen_scr and the tile 7 fil-
#    tered orography file generated by orog_fltr_scr (both of which have
#    a halo of width NHW cells).  The 4 output files are placed in the
#    temporary directory defined in WORKDIR_SHVE.  More specifically:
#
#    a) shave_exec is called to shave the halo in the tile 7 grid file
#       generated by grid_gen_scr down to a width of 3 cells and store
#       the result in a new grid file in WORKDIR_SHVE.
#
#    b) shave_exec is called to shave the halo in the tile 7 grid file
#       generated by grid_gen_scr down to a width of 4 cells and store
#       the result in a new grid file in WORKDIR_SHVE.
#
#    c) shave_exec is called to shave the halo in the tile 7 filtered
#       orography file generated by orog_fltr_scr down to a width of 0
#       cells (i.e. no halo) and store the result in a new filtered oro-
#       graphy file in WORKDIR_SHVE.
#
#    d) shave_exec is called to shave the halo in the tile 7 filtered
#       orography file generated by orog_fltr_scr down to a width of 4
#       cells and store the result in a new filtered orography file in
#       WORKDIR_SHVE.
#
# Run-time environment variables:
#
#    GLOBAL_VAR_DEFNS_FP
#    DATA

#
#-----------------------------------------------------------------------
#
# Source the variable definitions file and the bash utility functions.
#
#-----------------------------------------------------------------------
#
. $USHdir/source_util_funcs.sh
source_config_for_task "task_make_sfc_climo" ${GLOBAL_VAR_DEFNS_FP}
#
#-----------------------------------------------------------------------
#
# Save current shell options (in a global array).  Then set new options
# for this script/function.
#
#-----------------------------------------------------------------------
#
{ save_shell_opts; . $USHdir/preamble.sh; } > /dev/null 2>&1
#
#-----------------------------------------------------------------------
#
# Get the full path to the file in which this script/function is located 
# (scrfunc_fp), the name of that file (scrfunc_fn), and the directory in
# which the file is located (scrfunc_dir).
#
#-----------------------------------------------------------------------
#
scrfunc_fp=$( $READLINK -f "${BASH_SOURCE[0]}" )
scrfunc_fn=$( basename "${scrfunc_fp}" )
scrfunc_dir=$( dirname "${scrfunc_fp}" )
#
#-----------------------------------------------------------------------
#
# Print message indicating entry into script.
#
#-----------------------------------------------------------------------
#
print_info_msg "
========================================================================
Entering script:  \"${scrfunc_fn}\"
In directory:     \"${scrfunc_dir}\"

This is the ex-script for the task that generates surface fields from
climatology.
========================================================================"
#
#-----------------------------------------------------------------------
#
# Set OpenMP variables.
#
#-----------------------------------------------------------------------
#
export KMP_AFFINITY=${KMP_AFFINITY_MAKE_SFC_CLIMO}
export OMP_NUM_THREADS=${OMP_NUM_THREADS_MAKE_SFC_CLIMO}
export OMP_STACKSIZE=${OMP_STACKSIZE_MAKE_SFC_CLIMO}
#
#-----------------------------------------------------------------------
#
# Are these machine dependent??
#
#-----------------------------------------------------------------------
#
ulimit -s unlimited
#
#-----------------------------------------------------------------------
#
# Change location to the temporary directory.
#
#-----------------------------------------------------------------------
#
cd_vrfy $DATA
#
#-----------------------------------------------------------------------
#
# Create the namelist that the sfc_climo_gen code will read in.
#
# Question: Should this instead be created from a template file?
#
#-----------------------------------------------------------------------
#
cat << EOF > ./fort.41
&config
input_facsf_file="${FIXsfc}/facsf.1.0.nc"
input_substrate_temperature_file="${FIXsfc}/substrate_temperature.2.6x1.5.nc"
input_maximum_snow_albedo_file="${FIXsfc}/maximum_snow_albedo.0.05.nc"
input_snowfree_albedo_file="${FIXsfc}/snowfree_albedo.4comp.0.05.nc"
input_slope_type_file="${FIXsfc}/slope_type.1.0.nc"
input_soil_type_file="${FIXsfc}/soil_type.statsgo.0.05.nc"
input_vegetation_type_file="${FIXsfc}/vegetation_type.igbp.0.05.nc"
input_vegetation_greenness_file="${FIXsfc}/vegetation_greenness.0.144.nc"
mosaic_file_mdl="${FIXlam}/${CRES}${DOT_OR_USCORE}mosaic.halo${NH4}.nc"
orog_dir_mdl="${FIXlam}"
orog_files_mdl="${CRES}${DOT_OR_USCORE}oro_data.tile${TILE_RGNL}.halo${NH4}.nc"
halo=${NH4}
maximum_snow_albedo_method="bilinear"
snowfree_albedo_method="bilinear"
vegetation_greenness_method="bilinear"
/
EOF
#
#-----------------------------------------------------------------------
#
# Set the machine-dependent run command.
#
#-----------------------------------------------------------------------
#
eval ${PRE_TASK_CMDS}

if [ -z "${RUN_CMD_UTILS:-}" ] ; then
  print_err_msg_exit "\
  Run command was not set in machine file. \
  Please set RUN_CMD_UTILS for your platform"
else
  print_info_msg "$VERBOSE" "
  All executables will be submitted with command \'${RUN_CMD_UTILS}\'."
fi
#
#-----------------------------------------------------------------------
#
# Generate the surface climatology files.
#
#-----------------------------------------------------------------------
#
# Set the name and path to the executable and make sure that it exists.
#
exec_fn="sfc_climo_gen"
exec_fp="$EXECdir/${exec_fn}"
if [ ! -f "${exec_fp}" ]; then
  print_err_msg_exit "\
The executable (exec_fp) for generating the surface climatology files
does not exist:
  exec_fp = \"${exec_fp}\"
Please ensure that you've built this executable."
fi

PREP_STEP
eval ${RUN_CMD_UTILS} ${exec_fp} ${REDIRECT_OUT_ERR} || \
print_err_msg_exit "\
Call to executable (exec_fp) to generate surface climatology files returned
with nonzero exit code:
  exec_fp = \"${exec_fp}\""
POST_STEP
#
#-----------------------------------------------------------------------
#
# Move output files out of the temporary directory.
#
#-----------------------------------------------------------------------
#
case "$GTYPE" in

#
# Consider, global, stetched, and nested grids.
#
"global" | "stretch" | "nested")
#
# Move all files ending with ".nc" to the SFC_CLIMO_DIR directory.
# In the process, rename them so that the file names start with the C-
# resolution (followed by an underscore).
#
  for fn in *.nc; do
    if [[ -f $fn ]]; then
      mv_vrfy $fn ${SFC_CLIMO_DIR}/${CRES}_${fn}
    fi
  done
  ;;

#
# Consider regional grids.
#
"regional")
#
# Move all files ending with ".halo.nc" (which are the files for a grid
# that includes the specified non-zero-width halo) to the WORKDIR_SFC_-
# CLIMO directory.  In the process, rename them so that the file names
# start with the C-resolution (followed by a dot) and contain the (non-
# zero) halo width (in units of number of grid cells).
#
  for fn in *.halo.nc; do
    if [ -f $fn ]; then
      bn="${fn%.halo.nc}"
      mv_vrfy $fn ${SFC_CLIMO_DIR}/${CRES}.${bn}.halo${NH4}.nc
    fi
  done
#
# Move all remaining files ending with ".nc" (which are the files for a
# grid that doesn't include a halo) to the SFC_CLIMO_DIR directory.
# In the process, rename them so that the file names start with the C-
# resolution (followed by a dot) and contain the string "halo0" to indi-
# cate that the grids in these files do not contain a halo.
#
  for fn in *.nc; do
    if [ -f $fn ]; then
      bn="${fn%.nc}"
      mv_vrfy $fn ${SFC_CLIMO_DIR}/${CRES}.${bn}.halo${NH0}.nc
    fi
  done
  ;;

esac
#
#-----------------------------------------------------------------------
#
# Can these be moved to stage_static if this script is called before
# stage_static.sh????
# These have been moved.  Can delete the following after testing.
#
#-----------------------------------------------------------------------
#
python3 $USHdir/link_fix.py \
  --path-to-defns ${GLOBAL_VAR_DEFNS_FP} \
  --file-group "sfc_climo" || \
print_err_msg_exit "\
Call to function to create links to surface climatology files failed."
#
#-----------------------------------------------------------------------
#
# Print message indicating successful completion of script.
#
#-----------------------------------------------------------------------
#
print_info_msg "
========================================================================
All surface climatology files generated successfully!!!

Exiting script:  \"${scrfunc_fn}\"
In directory:    \"${scrfunc_dir}\"
========================================================================"
#
#-----------------------------------------------------------------------
#
# Restore the shell options saved at the beginning of this script/func-
# tion.
#
#-----------------------------------------------------------------------
#
{ restore_shell_opts; } > /dev/null 2>&1
