;
; **********************************************************************
;
; Define mathematical and physical constants.
;
; **********************************************************************
;
pi_geom = 4.0d*atan(1.0d)

degs_per_rad = 180.0d/pi_geom
rads_per_deg = 1.0d/degs_per_rad

meters_per_km = 1.0d+3
kms_per_meter = 1.0d/meters_per_km

meters2_per_km2 = meters_per_km^2
kms2_per_meter2 = 1.0d/meters2_per_km2


