RUN_ENVIR="community"
PREEXISTING_DIR_METHOD="rename"

PREDEF_GRID_NAME="RRFS_CONUS_25km"
QUILTING="TRUE"

CCPP_PHYS_SUITE="FV3_HRRR"
FCST_LEN_HRS="24"
LBC_SPEC_INTVL_HRS="3"

DATE_FIRST_CYCL="20150602"
DATE_LAST_CYCL="20150602"
CYCL_HRS=( "12" )

EXTRN_MDL_NAME_ICS="NAM"
EXTRN_MDL_NAME_LBCS="NAM"
USE_USER_STAGED_EXTRN_FILES="TRUE"
